"""empty message

Revision ID: 00df68e1c0a6
Revises: af627438e500
Create Date: 2023-04-21 22:58:25.320869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00df68e1c0a6'
down_revision = 'af627438e500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_matkul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('paralel', sa.String(length=1), nullable=False),
    sa.Column('dosen', sa.String(length=64), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('hari_kuliah', sa.Integer(), nullable=False),
    sa.Column('jam_kuliah', sa.DateTime(), nullable=False),
    sa.Column('lama_kuliah', sa.Integer(), nullable=False),
    sa.Column('hari_ujian', sa.Integer(), nullable=False),
    sa.Column('jam_ujian', sa.DateTime(), nullable=False),
    sa.Column('lama_ujian', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_matkul')
    # ### end Alembic commands ###
