"""empty message

Revision ID: 2136e8295656
Revises: 00df68e1c0a6
Create Date: 2023-05-08 20:57:40.751367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2136e8295656'
down_revision = '00df68e1c0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_matkul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singkatan', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('jadwal_kuliah', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jadwal_ujian', sa.Integer(), nullable=False))
        batch_op.drop_column('hari_ujian')
        batch_op.drop_column('jam_ujian')
        batch_op.drop_column('hari_kuliah')
        batch_op.drop_column('jam_kuliah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_matkul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_kuliah', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hari_kuliah', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jam_ujian', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hari_ujian', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('jadwal_ujian')
        batch_op.drop_column('jadwal_kuliah')
        batch_op.drop_column('singkatan')

    # ### end Alembic commands ###
