"""Initial Migrations.

Revision ID: af627438e500
Revises: 
Create Date: 2023-04-21 22:53:02.455482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af627438e500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_matkul',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('paralel', sa.String(length=1), nullable=True),
    sa.Column('dosen', sa.String(length=64), nullable=True),
    sa.Column('sks', sa.Integer(), nullable=True),
    sa.Column('hari_kuliah', sa.Integer(), nullable=True),
    sa.Column('jam_kuliah', sa.DateTime(), nullable=True),
    sa.Column('lama_kuliah', sa.Integer(), nullable=True),
    sa.Column('hari_ujian', sa.Integer(), nullable=True),
    sa.Column('jam_ujian', sa.DateTime(), nullable=True),
    sa.Column('lama_ujian', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_matkul')
    # ### end Alembic commands ###
